### ISSUE TITLE
[QUESTION] - Is it possible to search using multiple queries on different fields?

### ISSUE THREAD

**Issue by sujit-baniya** [micpst/minisearch#16]
In the following example:

```json
[{"code": "A000", "desc": "Cholera due to Vibrio cholerae 01, biovar cholerae", "work_item": 1}]
```

I was wondering if I could search like this: `"Cholera" IN "desc" AND "1" IN "work_item"`.

In this library, I could search using `SearchParams{Query: "Cholera", Properties: []string{"desc"}}`.

If I could search using multiple queries it would be great:

`SearchParams{Query: "Cholera", Properties: []string{"desc"}} AND SearchParams{Query: "1", Properties: []string{"work_item", Exact: true}}`

**Comment by micpst** [comment]
It's an interesting idea. I plan to add faceted search to this library, which would partially solve your problem. However, adding support for multiple queries, as you mentioned, is not currently on my list.

**Comment by sujit-baniya** [comment]
I'm not sure it's good implementation, I've implemented it this way to make it work as per my requirement at the moment.

```go
func (db *Store[Schema]) Search(params *Params) (Result[Schema], error) {
	if db.cache == nil {
		db.cache = make(map[uint64]map[int64]float64)
	}
	cachedKey := params.ToInt64()
	if cachedKey != 0 {
		if score, ok := db.cache[cachedKey]; ok {
			return db.prepareResult(score, params)
		}
	}
	idxParams, err := db.prepareFindParams(params)
	if err != nil {
		return Result[Schema]{}, err
	}
	queryScores := db.findDocumentIds(idxParams)
	if len(params.Extra) > 0 {
		idScores := make(map[int64]float64)
		for key, val := range params.Extra {
			param := &Params{
				Query:      fmt.Sprintf("%v", val),
				Properties: []string{key},
				BoolMode:   params.BoolMode,
				Exact:      true,
				Tolerance:  params.Tolerance,
				Language:   params.Language,
			}
			extraParams, err := db.prepareFindParams(param)
			if err != nil {
				return Result[Schema]{}, err
			}
			scores := db.findDocumentIds(extraParams)
			for id, _ := range scores {
				if v, k := queryScores[id]; k {
					idScores[id] = v
				}
			}
		}
		if cachedKey != 0 {
			db.cache[cachedKey] = idScores
		}
		return db.prepareResult(idScores, params)
	}
	if cachedKey != 0 {
		db.cache[cachedKey] = queryScores
	}
	return db.prepareResult(queryScores, params)
}

```

**Comment by micpst** [comment]
If it works for you, that's fine, but you are only binding queries to properties, in your example you wanted the second serach to be exact, with this implementation the rest of the parameters are shared between queries.

**Comment by sujit-baniya** [comment]
So, in above implementation what I tried to do is:
1) Search the main query with provided properties
2) Whenever there's any `extra` param `(map[string]any)`, I'm applying new query for the key, value (exact = true) of `param` 

That is individual query has it's own set of parameters

```go
data := readFileAsMap("icd10_codes.json")
	ftsSearch := search.New[any](&search.Config{
		TokenizerConfig: &tokenizer.Config{
			EnableStopWords: true,
			EnableStemming:  true,
		},
	})
	errs := ftsSearch.InsertBatch(data, 100)
	if len(errs) > 0 {
		panic(errs)
	}
	start := time.Now()
	s, err := ftsSearch.Search(&search.Params{
		Query:    "Diabetes in pregnancy first trimester",
		BoolMode: search.AND,
		Exact:    false,
		Extra: map[string]any{
			"code": "O24911",
		},
	})
	if err != nil {
		panic(err)
	}
	fmt.Println(s.Hits)
```
https://gist.github.com/sujit-baniya/3e23d90e44dc7cfbef09e66f80fc7a18

**Comment by micpst** [comment]
It looks a bit hacky, but as I said, if it works for you, that's fine. I'll close this issue, because there are no plans to change the library API to support such a query.
